persistence:
  storageClass: solar-sc

auth:
  existingSecret: postgres-creds # Name of the secret you created
  secretKeys:
    adminPasswordKey: admin-password # Key for the default 'postgres' user password

customUser:
  database: sonarqube
  existingSecret: postgres-creds # Name of the secret you created
  secretKeys:
    name: sonarqube-username # Key for the custom database user
    password: sonarqube-password # Key for the custom database user password