image:
  repository: "bitnamilegacy/postgresql"
volumePermissions:
  image:
  repository: "bitnamilegacy/os-shell"
metrics:
  image:
    repository : "bitnamilegacy/postgres-exporter"
global:
  storageClass: solar-sc
  postgresql:
    auth:
      existingSecret: postgres-creds # Name of the secret you created
      secretKeys:
        userPasswordKey: sonarqube-password # Key for the sonarqube user password
        adminPasswordKey: admin-password # Key for the default 'postgres' user password
      username: sonarqube # The desired default username
      database: sonarqube # The desired default database name