# Disable the default PostgreSQL database configuration

serviceAccount:
  create: false
postgresql:
  enabled: false

jdbcOverwrite:
  enabled: true
  jdbcUrl: "jdbc:postgresql://postgres-postgresql.sonarqube.svc.cluster.local:5432/sonarqube" # Add sslmode if TLS is enabled on PostgreSQL
  jdbcUsername: "sonarqube"
  jdbcSecretName: "postgres-creds" # Name of your Kubernetes secret
  jdbcSecretPasswordKey: "sonarqube-password" # postgres user password key in the secret

readinessProbe:
  timeoutSeconds: 10
livenessProbe:
  timeoutSeconds: 10
startupProbe:
  timeoutSeconds: 180

persistence:
  enabled: true
  storageClass: solar-sc

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sonarqube.sandbox.devvf.com
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/tags: "Environment=SANDBOX , Project=vf-grp-ias-dev-ias-sanbox , ManagedBy=vcisecretmanagement@vodafone.com , SecurityZone=DEV , Confidentiality=C2 , TaggingVersion=V2.4"
    alb.ingress.kubernetes.io/group.name: devops-tools
  hosts: 
    - name: sonarqube.sandbox.devvf.com
      path: /
      pathType: Prefix
community:
  enabled: true

monitoringPasscodeSecretName: "postgres-creds"
monitoringPasscodeSecretKey: "sonarqube-password"
