defaultVaultConnection:
   enabled: true
   address: "https://vault.vault.svc.cluster.local:8200"
   skipTLSVerify: false
   caCertSecret: vault-infra-metadata
   tlsServerName: secrets.sandbox.devvf.com